### ISSUE TITLE
Make checking the internet connectivity routine optional

### ISSUE THREAD

**Issue by mickrau** [friendly-bits/geoip-shell#12]
In my environment, i must use a HTTP proxy and a specific DNS server.

When running the install script, the "checking the internet connectivity" routine fails.

https://github.com/friendly-bits/geoip-shell/blob/bb930472205964ffa577f9d4c6a66d64e10ad1b6/geoip-shell-fetch.sh#L555-L565

When adding `""` to `ns` it works because the default DNS server is used. It is then of course no longer a real internet connectivity test.

Is this internet connectivity check really necessary (fetching the list would fail without internet anyway) or can it be at least optional?

The rest works fine, because curl takes the http_proxy environment variables into account.

**Comment by friendly-bits** [comment]
Hi, thank you for reporting this. Connectivity check is there for cases where there is an actual connectivity issue which the user is unaware of. So rather than waiting on geoip-shell to make multiple download attempts with fairly long timeouts, the user gets an immediate indication of the issue.

Currently (in version 0.5.3) the connectivity check relies on the nslookup utility and certain nameservers. There have been issues with this approach, so in the next release the mechanism of this check will be different, relying on the same utility used for download, and rather than checking DNS, actual connection test to the server will be performed. The next version will be available shortly (probably today or tomorrow). I will let you know here and hope that you don't mind testing with it and reporting back whether it solves this issue.

**Comment by friendly-bits** [comment]
@mickrau Version 0.5.4 is now released, could you test with it?

**Comment by mickrau** [comment]
@friendly-bits 
with version 0.5.4 it works well
